services:  
  runner:
    image: dnonakolesax/noted-runner:0.0.1
    ports:
      - "8700:8700"
      - "8702:8702"
    volumes:
      - ./configs:/configs      
      - /var/run/docker.sock:/var/run/docker.sock
      - noted-codes:/noted/codes  
    environment:
        CI_COMMIT_HASH: ${CI_COMMIT_HASH}
    networks: [noted-infra_infra-rmq]

networks:
  noted-infra_infra-rmq:
    external: true
volumes:  
  noted-codes: 
    external: true  
